[package]
name = "io_de_ser"
version = "0.0.1"
authors = ["Io-Maciek"]
description = "Crate that allows to read from and write to .io file format."
keywords = ["io", "file_format"]
edition = "2021"

[lib]

[dependencies]
deser = { path = "deser" }
paste = "1.0.14"
array-init = "2.1.0"